#:schema node_modules/wrangler/config-schema.json
name = "django-on-workers"
main = "src/asgi.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-10-17"

assets = { directory = "./staticfiles/" }

[[d1_databases]]
binding = "DB"
database_name = "YOUR_DATABASE_NAME"
database_id = "bd87ee85-d9a3-488b-aea0-c3c85ac4a911"
